github: [Hisoka-Morrou, Risz124] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: Risz123 # Replace with a single Patreon username
ko_fi: cak_haho # Replace with a single Ko-fi username
custom: ['https://whatsapp.com/channel/0029VapGzuTJUM2h0WrgZA3L'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
